### ISSUE TITLE
'Flips took too long to process and timed out' doesn't always correctly remove the progress bar

### ISSUE THREAD

**Issue by Barragek0** [Vikame/SkyblockBINSniper#11]
![image](https://user-images.githubusercontent.com/24503018/136142000-fa5027c2-d167-4f67-8c9d-9d52894061e4.png)

**Comment by Vikame** [comment]
Commit [7d51a93](https://github.com/Vikame/SkyblockBINSniper/commit/7d51a93fdc21254ad38bd5677da0397725ff2e66) should fix this. You can re-open this issue if it still occurs.
