### ISSUE TITLE
'Flips took too long to process'

### ISSUE THREAD

**Issue by Barragek0** [Vikame/SkyblockBINSniper#13]
After running the script for 30 minutes to an hour, not pasting the commands in-game most of the time and leaving it to timeout, this happens. The script seemingly freezes and refuses to process anymore pages. This is with 'debug' on, so it should be outputting every page it successfully parses.
![image](https://user-images.githubusercontent.com/24503018/136321358-5b912cbb-7791-44b6-b3e8-3c54602c5458.png)

**Comment by Barragek0** [comment]
Pretty certain its a misconfiguration related to the script, restarting it immediately fixed the problem. It was stuck in that error cycle for ages this time.

**Comment by Barragek0** [comment]
![image](https://user-images.githubusercontent.com/24503018/136329251-9f54f02a-825d-45dc-ad6f-967669cd932d.png)

**Comment by Barragek0** [comment]
> 
> 
> Can you send me your current configuration file so I can take a look at the exact setup you have?

```
#Skyblock BIN Sniper configuration data
#Mon Oct 04 02:40:30 BST 2021
TIMEOUT=20,000
SOUND_WHEN_FLIP_FOUND=true
MIN_ITEMS_ON_MARKET=3
MIN_PROFIT_PERCENTAGE=150
FORCE_NO_CACHE_API_REQUESTS=true
IGNORE_FURNITURE=true
ITERATE_RESULTS_TO_CLIPBOARD=true
MIN_BIN_PRICE=200,000
MAX_BIN_PRICE=2,000,000
EXPLICIT_GC_AFTER_FLIP=false
IGNORE_RECOMB=true
MAX_FLIPS_TO_SHOW=5
IGNORE_SKINS=true
IGNORE_REFORGES=true
USE_GZIP_COMPRESSION_ON_API_REQUESTS=true
CACHE_ATOMIC_OBJECTS=true
IGNORE_USED_CAKE_SOULS=true
POOLED_THREAD_COUNT=8
IGNORE_COSMETICS=true
MIN_PROFIT_AMOUNT=500,000
NOTIFICATION_WHEN_FLIP_FOUND=false
OLD_THRESHOLD=180,000
IGNORE_HOT_POTATO=true
IGNORE_STARS=true
KEY_LISTENER_DEBUG=false
DEBUG=true
```

**Comment by Vikame** [comment]
[3b06f3e](https://github.com/Vikame/SkyblockBINSniper/commit/3b06f3e233ce9b1f07732857b18229887c2c9900) should fix this!
