### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by Andesine** [Vikame/SkyblockBINSniper#16]
Is it possible for me to make it auto open the buy menu when the potential “flip” appears? I’m not that good with coding and stuff but if it’s possible I would like a reply :)

**Comment by Vikame** [comment]
I think this is where I personally draw the line on software like this. While it'd technically be possible to achieve, it's not something I am willing to support as it is effectively just a macro. This may end up driving some people away from the project, but I believe snipers are already skirting the line of what should be considered against the rules and so adding a macro to that certainly crosses that line. Sorry for that!
