### ISSUE TITLE
'Commands were not pasted before we started a new flip attempt' causes script to slow down significantly

### ISSUE THREAD

**Issue by Barragek0** [Vikame/SkyblockBINSniper#7]

**Comment by Barragek0** [comment]
There is definitely something weird going on related to this, but it seems really inconsistent / strange.
![image](https://user-images.githubusercontent.com/24503018/136164836-b2391a6c-c924-4df0-8231-1eb8d9552af8.png)

After that message, the search starts taking much longer but not all of the time, it feels like there's more than one thread running the same code or something because of weird formatting errors like this that happen when this issue occurs. This is also what was causing the /viewauction null to happen, it wasn't related to the other issue.

**Comment by Vikame** [comment]
Followup: [7d51a93](https://github.com/Vikame/SkyblockBINSniper/commit/7d51a93fdc21254ad38bd5677da0397725ff2e66) should be a further optimization.
