### ISSUE TITLE
First item gets skipped past when using iterate_results_using_clipboard

### ISSUE THREAD

**Issue by Barragek0** [Vikame/SkyblockBINSniper#9]

**Comment by Vikame** [comment]
Can you check if [this patch](https://github.com/Vikame/SkyblockBINSniper/commit/23a536434b40870eea68fc32ad75d7eaeae368bb) had any effect on this?

**Comment by Barragek0** [comment]
Commit 23a536434b40870eea68fc32ad75d7eaeae368bb fixed this
